name: Test Workflow 5

on: 
    pull_request:
        types: 
            - opened
            - synchronize
            - closed
        branches: 
            - main


jobs:
    echo:
        runs-on: ubuntu-latest
        steps: 
            - run: echo "Running wheneve a PR is open or synchronized or close and base branch is main"
