name: Test Workflow 12

on:
  push:

jobs:
  test-multi-matrix-job:
    name: ${{matrix.os}} ${{matrix.version}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [8, 11, 17, 21]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.version }}
