name: Test Workflow 4

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Code Checkout
              uses: actions/checkout@v4
            - name: Print Folders
              run: ls
            # 0. Checkout the code from repository
            # 1. Install the dependency of our react application
            # 2. Execute automated tests