name: Test Workflow 1

on: 
    workflow_dispatch: 

jobs:
    test-job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Hello 1
              run: echo "Hello 1!"
    
    test-job-2:
        runs-on: ubuntu-latest
        steps:
            - name: Exit Step
              run: exit 0;

            - name: Hello 2
              run: echo "Hello 2!";