name: Test Workflow 12

on:
  push:

jobs:
  test-multi-matrix-job:
    strategy:
      fail-fast: false
      matrix:
        num1: [1, 2, 3, 4]
        num2: [5, 6, 7, 8]
        num3: [9, 10, 11, 12]
    runs-on: ubuntu-latest
    steps:
      - run: echo $(( ${{matrix.num1}} * ${{matrix.num2}} * ${{matrix.num3}}))
