name: Test Workflow 5

on: 
    pull_request:
        types: 
            - opened
            - synchronize
        branches: 
            - main


jobs:
    echo:
        runs-on: ubuntu-linux
        steps: 
            - run: echo "Running wheneve a PR is open or synchronized and base branch is main"
