name: Test Workflow 3

on: push

jobs:
    test-job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Print OS
              run: |
                echo $RUNNER_OS
    test-job-2:
        runs-on: windows-latest
        steps:
            - name: Print OS
              run: |
                echo $RUNNER_OS