name: Test Workflow 5

on: 
    workflow_dispatch: 


jobs:
    echo:
        runs-on: ubuntu-latest
        steps: 
            - run: echo "Running whenever a PR is open or synchronized or close and base branch is main"
