name: Test Workflow 10

on:
  push:
  workflow_dispatch:

jobs:
  test-job-1:
    runs-on: ubuntu-latest
    outputs:
      num1: ${{steps.step1.outputs.NUM1}}
    steps:
      - name: Step 1
        id: step1
        run: echo "NUM1=4" >> "$GITHUB_OUTPUT"
  test-job-2:
    runs-on: ubuntu-latest
    needs: test-job-1
    steps:
      - name: Step 1
        run: echo ${{needs.test-job-1.outputs.num1}}
